"""
Mock database cho Trợ Lý Đi Chợ Thông Minh.
Tách riêng data layer — dễ swap sang real database sau.
"""

RECIPES = {
    "pho_bo": {
        "name": "Phở Bò",
        "servings": 4,
        "ingredients": [
            {"item": "bánh phở", "quantity": "800g"},
            {"item": "thịt bò", "quantity": "500g"},
            {"item": "xương bò", "quantity": "1kg"},
            {"item": "hành tây", "quantity": "2 củ"},
            {"item": "gừng", "quantity": "1 củ"},
            {"item": "quế", "quantity": "1 thanh"},
            {"item": "hoa hồi", "quantity": "3 cái"},
            {"item": "nước mắm", "quantity": "3 muỗng canh"},
            {"item": "hành lá", "quantity": "1 bó"},
            {"item": "giá đỗ", "quantity": "200g"},
            {"item": "rau mùi", "quantity": "1 bó"},
        ],
        "time": "3 tiếng",
    },
    "bun_bo_hue": {
        "name": "Bún Bò Huế",
        "servings": 4,
        "ingredients": [
            {"item": "bún tươi", "quantity": "1kg"},
            {"item": "thịt bò bắp", "quantity": "400g"},
            {"item": "giò heo", "quantity": "2 cái"},
            {"item": "chả cua", "quantity": "200g"},
            {"item": "sả", "quantity": "5 cây"},
            {"item": "mắm ruốc", "quantity": "2 muỗng canh"},
            {"item": "ớt bột", "quantity": "1 muỗng canh"},
            {"item": "hành tây", "quantity": "1 củ"},
            {"item": "rau muống", "quantity": "1 bó"},
            {"item": "bắp chuối", "quantity": "1 bắp"},
        ],
        "time": "2.5 tiếng",
    },
    "com_tam": {
        "name": "Cơm Tấm Sườn Bì Chả",
        "servings": 2,
        "ingredients": [
            {"item": "gạo tấm", "quantity": "300g"},
            {"item": "sườn heo", "quantity": "4 miếng"},
            {"item": "bì heo", "quantity": "150g"},
            {"item": "trứng", "quantity": "2 quả"},
            {"item": "thịt heo xay", "quantity": "200g"},
            {"item": "nước mắm", "quantity": "3 muỗng canh"},
            {"item": "đường", "quantity": "2 muỗng canh"},
            {"item": "tỏi", "quantity": "5 tép"},
            {"item": "dưa leo", "quantity": "1 quả"},
            {"item": "cà chua", "quantity": "1 quả"},
            {"item": "mỡ hành", "quantity": "2 muỗng canh"},
        ],
        "time": "1 tiếng",
    },
    "ga_kho_gung": {
        "name": "Gà Kho Gừng",
        "servings": 3,
        "ingredients": [
            {"item": "đùi gà", "quantity": "500g"},
            {"item": "gừng", "quantity": "1 củ to"},
            {"item": "nước mắm", "quantity": "2 muỗng canh"},
            {"item": "đường", "quantity": "1 muỗng canh"},
            {"item": "tỏi", "quantity": "3 tép"},
            {"item": "tiêu", "quantity": "1 muỗng cà phê"},
            {"item": "hành tím", "quantity": "2 củ"},
        ],
        "time": "45 phút",
    },
    "canh_chua_ca": {
        "name": "Canh Chua Cá",
        "servings": 4,
        "ingredients": [
            {"item": "cá lóc", "quantity": "500g"},
            {"item": "thơm (dứa)", "quantity": "1/2 quả"},
            {"item": "cà chua", "quantity": "2 quả"},
            {"item": "đậu bắp", "quantity": "100g"},
            {"item": "giá đỗ", "quantity": "150g"},
            {"item": "me", "quantity": "50g"},
            {"item": "rau ngổ", "quantity": "1 bó"},
            {"item": "ớt", "quantity": "2 quả"},
            {"item": "nước mắm", "quantity": "2 muỗng canh"},
            {"item": "đường", "quantity": "1 muỗng canh"},
        ],
        "time": "40 phút",
    },
}

STORE_INVENTORY = {
    "bánh phở":      {"price": 25000,  "unit": "kg",    "in_stock": True},
    "bún tươi":      {"price": 20000,  "unit": "kg",    "in_stock": True},
    "thịt bò":       {"price": 280000, "unit": "kg",    "in_stock": True},
    "thịt bò bắp":   {"price": 300000, "unit": "kg",    "in_stock": True},
    "xương bò":      {"price": 80000,  "unit": "kg",    "in_stock": True},
    "đùi gà":        {"price": 75000,  "unit": "kg",    "in_stock": True},
    "sườn heo":      {"price": 120000, "unit": "kg",    "in_stock": True},
    "giò heo":       {"price": 90000,  "unit": "kg",    "in_stock": False},   # HẾT
    "cá lóc":        {"price": 85000,  "unit": "kg",    "in_stock": True},
    "thịt heo xay":  {"price": 95000,  "unit": "kg",    "in_stock": True},
    "bì heo":        {"price": 60000,  "unit": "kg",    "in_stock": True},
    "chả cua":       {"price": 45000,  "unit": "200g",  "in_stock": True},
    "gạo tấm":       {"price": 30000,  "unit": "kg",    "in_stock": True},
    "trứng":         {"price": 3500,   "unit": "quả",   "in_stock": True},
    "hành tây":      {"price": 15000,  "unit": "kg",    "in_stock": True},
    "hành tím":      {"price": 40000,  "unit": "kg",    "in_stock": True},
    "hành lá":       {"price": 5000,   "unit": "bó",    "in_stock": True},
    "tỏi":           {"price": 60000,  "unit": "kg",    "in_stock": True},
    "gừng":          {"price": 30000,  "unit": "kg",    "in_stock": True},
    "sả":            {"price": 10000,  "unit": "bó",    "in_stock": True},
    "ớt":            {"price": 20000,  "unit": "kg",    "in_stock": True},
    "ớt bột":        {"price": 15000,  "unit": "100g",  "in_stock": True},
    "tiêu":          {"price": 200000, "unit": "kg",    "in_stock": True},
    "quế":           {"price": 10000,  "unit": "thanh", "in_stock": True},
    "hoa hồi":       {"price": 5000,   "unit": "3 cái", "in_stock": True},
    "nước mắm":      {"price": 35000,  "unit": "chai",  "in_stock": True},
    "mắm ruốc":      {"price": 25000,  "unit": "hũ",    "in_stock": False},   # HẾT
    "đường":         {"price": 18000,  "unit": "kg",    "in_stock": True},
    "me":            {"price": 20000,  "unit": "100g",  "in_stock": True},
    "giá đỗ":        {"price": 8000,   "unit": "kg",    "in_stock": True},
    "rau mùi":       {"price": 5000,   "unit": "bó",    "in_stock": True},
    "rau muống":     {"price": 7000,   "unit": "bó",    "in_stock": True},
    "rau ngổ":       {"price": 5000,   "unit": "bó",    "in_stock": True},
    "bắp chuối":     {"price": 10000,  "unit": "bắp",   "in_stock": True},
    "cà chua":       {"price": 15000,  "unit": "kg",    "in_stock": True},
    "dưa leo":       {"price": 12000,  "unit": "kg",    "in_stock": True},
    "đậu bắp":       {"price": 18000,  "unit": "kg",    "in_stock": True},
    "thơm (dứa)":    {"price": 15000,  "unit": "quả",   "in_stock": True},
    "mỡ hành":       {"price": 10000,  "unit": "hũ",    "in_stock": True},
}

SUBSTITUTIONS = {
    "giò heo":     ["chân giò heo (đông lạnh)", "thịt heo nạc vai"],
    "mắm ruốc":   ["mắm tôm", "mắm nêm"],
    "rau muống":   ["rau cải", "rau mồng tơi"],
    "thịt bò":     ["thịt trâu", "thịt bò đông lạnh"],
    "cá lóc":      ["cá diêu hồng", "cá ba sa"],
    "bắp chuối":   ["rau muống", "giá đỗ (thêm)"],
    "rau ngổ":     ["rau răm", "ngò gai"],
    "me":          ["bột me", "chanh"],
    "chả cua":     ["chả lụa", "chả Huế"],
    "thơm (dứa)":  ["cà chua (thêm)", "me"],
}